name: Build
on:
 push:
  branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: Node JS Sonar Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Cache node modules
      #   id: cache-nodemodules
      #   uses: actions/cache@v3
      #   env:
      #     cache-name: cache-node-modules
      #   with:
      #     path: ${{ github.workspace }}/node-express-apis-with-tests/node_modules
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      

      - name: Install the dependencies
        run: cd node-express-apis-with-tests && npm install
  
      - name: Test and coverage
        run: cd node-express-apis-with-tests && npm jest --coverage

      - name: SonarCloud Scan
        with:
          projectBaseDir: ./
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

